Repository g12-4soat/techmedicos-api, pull requests merged in 2024-07, with the labels that each got.

#1 criação da estrutura do projeto
  src/TechMedicos/.dockerignore
  src/TechMedicos/Adapter/Driven/TechMedicos.Adapter.AWS.SecretsManager/TechMedicos.Adapter.AWS.SecretsManager.csproj
  src/TechMedicos/Adapter/Driven/TechMedicos.Adapter.DynamoDB/TechMedicos.Adapter.DynamoDB.csproj
  src/TechMedicos/Adapter/Driver/TechMedicos.API/Dockerfile
  src/TechMedicos/Adapter/Driver/TechMedicos.API/Program.cs
  src/TechMedicos/Adapter/Driver/TechMedicos.API/Properties/launchSettings.json
  src/TechMedicos/Adapter/Driver/TechMedicos.API/TechMedicos.API.csproj
  src/TechMedicos/Adapter/Driver/TechMedicos.API/TechMedicos.API.http
  src/TechMedicos/Adapter/Driver/TechMedicos.API/appsettings.Development.json
  src/TechMedicos/Adapter/Driver/TechMedicos.API/appsettings.json
  src/TechMedicos/Core/TechMedicos.Application/TechMedicos.Application.csproj
  src/TechMedicos/Core/TechMedicos.Core/DomainException.cs
  src/TechMedicos/Core/TechMedicos.Core/Entity.cs
  src/TechMedicos/Core/TechMedicos.Core/IAggregateRoot.cs
  src/TechMedicos/Core/TechMedicos.Core/IRepository.cs
  src/TechMedicos/Core/TechMedicos.Core/TechMedicos.Core.csproj
  src/TechMedicos/Core/TechMedicos.Domain/TechMedicos.Domain.csproj
  src/TechMedicos/TechMedicos.sln
  tests/TechMedicos.UnitTests/TechMedicos.UnitTests.csproj
Labels: enhancement

#5 add manifestos k8s
  k8s/apply-all.sh
  k8s/deployments/techmedicos-api-deployment.yaml
  k8s/metrics/metrics.yaml
  k8s/techmedicos-configmap.yaml
  k8s/techmedicos-namespace.yaml
Labels: enhancement

#11 add pipeline CI/CD para testes
  .github/workflows/pipeline-cicd.yml
  src/TechMedicos/Adapter/Driver/TechMedicos.API/Dockerfile
  src/TechMedicos/Dockerfile
Labels: enhancement

#13 add gateways
  src/TechMedicos/Core/TechMedicos.Application/Gateways/ConsultaGateway.cs
  src/TechMedicos/Core/TechMedicos.Application/Gateways/Interfaces/IConsultaGateway.cs
  src/TechMedicos/Core/TechMedicos.Application/Gateways/Interfaces/IMedicoGateway.cs
  src/TechMedicos/Core/TechMedicos.Application/Gateways/Interfaces/IPacienteGateway.cs
  src/TechMedicos/Core/TechMedicos.Application/Gateways/MedicoGateway.cs
  src/TechMedicos/Core/TechMedicos.Application/Gateways/PacienteGateway.cs
  src/TechMedicos/Core/TechMedicos.Application/TechMedicos.Application.csproj
Labels: enhancement

#2 inicio da configuração, endpoints e secrets
  src/TechMedicos/Adapter/Driven/TechMedicos.Adapter.AWS.SecretsManager/AmazonSecretsManagerConfigurationProvider.cs
  src/TechMedicos/Adapter/Driven/TechMedicos.Adapter.AWS.SecretsManager/AmazonSecretsManagerConfigurationProviderExtensions.cs
  src/TechMedicos/Adapter/Driven/TechMedicos.Adapter.AWS.SecretsManager/AmazonSecretsManagerConfigurationSource.cs
  src/TechMedicos/Adapter/Driven/TechMedicos.Adapter.AWS.SecretsManager/TechLanchesCognitoSecrets.cs
  src/TechMedicos/Adapter/Driven/TechMedicos.Adapter.AWS.SecretsManager/TechMedicos.Adapter.AWS.SecretsManager.csproj
  src/TechMedicos/Adapter/Driven/TechMedicos.Adapter.DynamoDB/Models/MedicoDbModel.cs
  src/TechMedicos/Adapter/Driven/TechMedicos.Adapter.DynamoDB/Repositories/MedicoRepository.cs
  src/TechMedicos/Adapter/Driver/TechMedicos.API/Configuration/ApplicationBuilderConfig.cs
  src/TechMedicos/Adapter/Driver/TechMedicos.API/Configuration/AuthenticationConfig.cs
  src/TechMedicos/Adapter/Driver/TechMedicos.API/Configuration/DependecyInjectionConfig.cs
  src/TechMedicos/Adapter/Driver/TechMedicos.API/Configuration/HealthCheckConfig.cs
  src/TechMedicos/Adapter/Driver/TechMedicos.API/Configuration/MapEndpointsConfig.cs
  src/TechMedicos/Adapter/Driver/TechMedicos.API/Configuration/RegisterMapsConfig.cs
  src/TechMedicos/Adapter/Driver/TechMedicos.API/Configuration/SwaggerConfig.cs
  src/TechMedicos/Adapter/Driver/TechMedicos.API/Constantes/Constante.cs
  src/TechMedicos/Adapter/Driver/TechMedicos.API/Endpoints/ConsultaEndpoints.cs
  src/TechMedicos/Adapter/Driver/TechMedicos.API/Endpoints/MedicoEndpoints.cs
  src/TechMedicos/Adapter/Driver/TechMedicos.API/Middlewares/GlobalErrorHandlingMiddleware.cs
  src/TechMedicos/Adapter/Driver/TechMedicos.API/Program.cs
  src/TechMedicos/Adapter/Driver/TechMedicos.API/TechMedicos.API.csproj
  src/TechMedicos/Core/TechMedicos.Application/Controllers/ConsultaController.cs
  src/TechMedicos/Core/TechMedicos.Application/Controllers/Interfaces/IConsultaController.cs
  src/TechMedicos/Core/TechMedicos.Application/Controllers/Interfaces/IMedicoController.cs
  src/TechMedicos/Core/TechMedicos.Application/Controllers/MedicoController.cs
  src/TechMedicos/Core/TechMedicos.Application/DTOs/AgendaMedicaRequestDTO.cs
  src/TechMedicos/Core/TechMedicos.Application/DTOs/AgendaMedicaResponseDTO.cs
  src/TechMedicos/Core/TechMedicos.Application/DTOs/ConsultaAtualizarRequestDTO.cs
  src/TechMedicos/Core/TechMedicos.Application/DTOs/ConsultaCadastrarRequestDTO.cs
  src/TechMedicos/Core/TechMedicos.Application/DTOs/ConsultaResponseDTO.cs
  src/TechMedicos/Core/TechMedicos.Application/DTOs/ErrorResponseDTO.cs
  src/TechMedicos/Core/TechMedicos.Application/DTOs/HorarioDisponivelRequestDTO.cs
  src/TechMedicos/Core/TechMedicos.Application/DTOs/HorarioDisponivelResponseDTO.cs
  src/TechMedicos/Core/TechMedicos.Application/DTOs/MedicoResponseDTO.cs
  src/TechMedicos/Core/TechMedicos.Application/TechMedicos.Application.csproj
  src/TechMedicos/Core/TechMedicos.Domain/Aggregates/Medico.cs
  src/TechMedicos/Core/TechMedicos.Domain/ValueObjects/AgendaMedica.cs
  tests/TechMedicos.UnitTests/Domain/MedicoTest.cs
Labels: enhancement

#16 rascunho use cases
  src/TechMedicos/Adapter/Driven/TechMedicos.Adapter.DynamoDB/Repositories/ConsultaRepository.cs
  src/TechMedicos/Adapter/Driven/TechMedicos.Adapter.DynamoDB/Repositories/MedicoRepository.cs
  src/TechMedicos/Adapter/Driver/TechMedicos.API/Configuration/DependecyInjectionConfig.cs
  src/TechMedicos/Adapter/Driver/TechMedicos.API/Endpoints/ConsultaEndpoints.cs
  src/TechMedicos/Adapter/Driver/TechMedicos.API/Endpoints/MedicoEndpoints.cs
  src/TechMedicos/Adapter/Driver/TechMedicos.API/TechMedicos.API.csproj
  src/TechMedicos/Core/TechMedicos.Application/Controllers/ConsultaController.cs
  src/TechMedicos/Core/TechMedicos.Application/Controllers/Interfaces/IConsultaController.cs
  src/TechMedicos/Core/TechMedicos.Application/Controllers/Interfaces/IMedicoController.cs
  src/TechMedicos/Core/TechMedicos.Application/Controllers/MedicoController.cs
  src/TechMedicos/Core/TechMedicos.Application/DTOs/ConsultaCadastrarRequestDTO.cs
  src/TechMedicos/Core/TechMedicos.Application/DTOs/ConsultaResponseDTO.cs
  src/TechMedicos/Core/TechMedicos.Application/Gateways/ConsultaGateway.cs
  src/TechMedicos/Core/TechMedicos.Application/Gateways/Interfaces/IConsultaGateway.cs
  src/TechMedicos/Core/TechMedicos.Application/Ports/Repositories/IConsultaRepository.cs
  src/TechMedicos/Core/TechMedicos.Application/TechMedicos.Application.csproj
  src/TechMedicos/Core/TechMedicos.Application/UseCases/Consultas/ConsultaUseCases.cs
  src/TechMedicos/Core/TechMedicos.Application/UseCases/Medicos/MedicoUseCases.cs
  src/TechMedicos/Core/TechMedicos.Application/UseCases/Pacientes/PacienteUseCases.cs
  src/TechMedicos/Core/TechMedicos.Domain/Aggregates/Medico.cs
  tests/TechMedicos.UnitTests/Domain/MedicoTest.cs
Labels: enhancement

#20 retorno dto com as informações do dynamo
  src/TechMedicos/Adapter/Driven/TechMedicos.Adapter.DynamoDB/Models/Converter/AgendaMedicaConverter.cs
  src/TechMedicos/Adapter/Driver/TechMedicos.API/Configuration/RegisterMapsConfig.cs
  src/TechMedicos/Core/TechMedicos.Application/Controllers/Interfaces/IMedicoController.cs
  src/TechMedicos/Core/TechMedicos.Application/Controllers/MedicoController.cs
  src/TechMedicos/Core/TechMedicos.Application/DTOs/MedicoResponseDTO.cs
Labels: enhancement

#23 Feature/fix consultas
  src/TechMedicos/Adapter/Driven/TechMedicos.Adapter.DynamoDB/Models/MedicoDbModel.cs
  src/TechMedicos/Adapter/Driven/TechMedicos.Adapter.DynamoDB/Models/PacienteDbModel.cs
  src/TechMedicos/Adapter/Driven/TechMedicos.Adapter.DynamoDB/Repositories/ConsultaRepository.cs
  src/TechMedicos/Adapter/Driver/TechMedicos.API/Configuration/RegisterMapsConfig.cs
  src/TechMedicos/Core/TechMedicos.Application/Controllers/ConsultaController.cs
  src/TechMedicos/Core/TechMedicos.Application/DTOs/ConsultaAtualizarRequestDTO.cs
  src/TechMedicos/Core/TechMedicos.Application/DTOs/ConsultaResponseDTO.cs
  src/TechMedicos/Core/TechMedicos.Application/DTOs/PacienteResponseDTO.cs
  src/TechMedicos/Core/TechMedicos.Application/TechMedicos.Application.csproj
  src/TechMedicos/Core/TechMedicos.Application/UseCases/Consultas/ConsultaUseCases.cs
  src/TechMedicos/Core/TechMedicos.Application/UseCases/Medicos/MedicoUseCases.cs
  src/TechMedicos/Core/TechMedicos.Domain/Aggregates/Consulta.cs
Labels: bug, enhancement

#24 correções consulta
  src/TechMedicos/Adapter/Driven/TechMedicos.Adapter.DynamoDB/Models/ConsultaDbModel.cs
  src/TechMedicos/Adapter/Driven/TechMedicos.Adapter.DynamoDB/Repositories/ConsultaRepository.cs
  src/TechMedicos/Core/TechMedicos.Application/UseCases/Consultas/ConsultaUseCases.cs
  src/TechMedicos/Core/TechMedicos.Domain/Aggregates/Consulta.cs
Labels: bug

#25 correção teste
  tests/TechMedicos.UnitTests/Domain/ConsultaTest.cs
Labels: bug

#26 correções de justificativa padrao
  src/TechMedicos/Core/TechMedicos.Application/DTOs/ConsultaResponseDTO.cs
  src/TechMedicos/Core/TechMedicos.Domain/Aggregates/Consulta.cs
  tests/TechMedicos.UnitTests/Domain/ConsultaTest.cs
Labels: bug

#27 Feature/auth tokens
  src/TechMedicos/Adapter/Driver/TechMedicos.API/Configuration/ApplicationBuilderConfig.cs
  src/TechMedicos/Adapter/Driver/TechMedicos.API/Configuration/DependecyInjectionConfig.cs
  src/TechMedicos/Adapter/Driver/TechMedicos.API/Endpoints/ConsultaEndpoints.cs
  src/TechMedicos/Adapter/Driver/TechMedicos.API/Endpoints/MedicoEndpoints.cs
  src/TechMedicos/Adapter/Driver/TechMedicos.API/Middlewares/JwtTokenMiddleware.cs
  src/TechMedicos/Adapter/Driver/TechMedicos.API/Program.cs
  src/TechMedicos/Core/TechMedicos.Domain/Enums/StatusConsulta.cs
  src/TechMedicos/Core/TechMedicos.Domain/Enums/TipoUsuario.cs
  src/TechMedicos/Core/TechMedicos.Domain/ValueObjects/Crm.cs
Labels: bug, enhancement

#33 Hotfix/filtros medico
  src/TechMedicos/Adapter/Driven/TechMedicos.Adapter.DynamoDB/Models/MedicoDbModel.cs
  src/TechMedicos/Adapter/Driven/TechMedicos.Adapter.DynamoDB/Repositories/MedicoRepository.cs
  src/TechMedicos/Adapter/Driver/TechMedicos.API/Configuration/RegisterMapsConfig.cs
  src/TechMedicos/Adapter/Driver/TechMedicos.API/Endpoints/MedicoEndpoints.cs
  src/TechMedicos/Adapter/Driver/TechMedicos.API/TechMedicos.API.http
  src/TechMedicos/Core/TechMedicos.Application/Controllers/Interfaces/IMedicoController.cs
  src/TechMedicos/Core/TechMedicos.Application/Controllers/MedicoController.cs
  src/TechMedicos/Core/TechMedicos.Application/DTOs/MedicoResponseDTO.cs
  src/TechMedicos/Core/TechMedicos.Domain/Aggregates/Medico.cs
  src/TechMedicos/Core/TechMedicos.Domain/Enums/EspecialidadesMedicas.cs
Labels: documentation, enhancement
